services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=$DB_SCHEMA'
      - 'MYSQL_ROOT_PASSWORD=$DB_PASSWORD'
      - 'MYSQL_USER=$DB_USERNAME'
      - 'MYSQL_PASSWORD=$DB_PASSWORD'
    ports:
      - '3307:3306'
